version: '3.9'

services:
  db:
    image: postgres:15
    container_name: shadapp-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shadapp
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: shadapp-app
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - .env.production
    depends_on:
      - db

volumes:
  db_data:
